import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Transition from "./Transition.js";
import { AnimatePresence } from 'framer-motion';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>

        <Transition>{children}</Transition>
       
        
      </body>
    </html>
  );
}
